### ISSUE TITLE
Unable to figure out how to use pre-trained model

### ISSUE THREAD

**Issue by cnyi** [Guillermo-Hidalgo-Gadea/UQOAB#1]
Hi!
I wasn't sure exactly where to ask this question, but I am currently attempting to use your UQOAB/Facial Expression Analysis/DeepLabCut/exported-models/ to see if it would work on my videos of human faces, but I just can't seem to figure out how to do it. I copied your config.yaml file and all of the data stored in exported-models, then I opened it through "load project" in the DLC GUI. 

I then open my project in Google Colab since this is my only access to a GPU- once I am here, I am completely lost. I am unable to evaluate the network or test my own videos. Do I need to retrain the network? In to config file, it seems like the videos are locally stored so I assumed the trained network was already available through the index/meta data. Is there something I am missing? Do I need to unzip a file?

It seems like I'm missing the larger instructions of how to use your model- apologies because I am an unexperienced undergrad when it comes to software.

Thank you!

**Comment by Guillermo-Hidalgo-Gadea** [comment]
Hi @cnyi ,
thanks for rising the issue, this can be a legitimate impasse, sorry for the missing instructions. 
The exported model was intended to be used in DLC-live wich needs `<path to exported model directory>`, but in your case I guess you would be fine just using the regular snapshots (see [here](https://github.com/DeepLabCut/DeepLabCut/issues/241#issuecomment-472146840)) and my original directory structure.  
 
Here is how: 

1. Download the new project directory I just updated to `\UQOAB\Facial Expression Analysis\DeepLabCut\DLC-Guillermo-2021-04-14`. Make sure to get this one right, specially if you move your local project to google drive and back.
2. Change `project_path:` in the config.yaml to the path to your project directory 
3. Ignore the missing `evaluation-results`, `labeled-data`, `training-datasets`, and `videos` directories. The `config.yaml` file will directly point you to the latest snapshot of the latest trained iteration, i.e. `snapshot-1030000.data-00000-of-00001`. `snapshot-1030000.index` and `snapshot-1030000.meta`.
4. Start your colab notebook and set the `config_path` or `path_config_file` to the location of the config.yaml within your google drive

I hope that helps, let me know how it goes.
